### ISSUE TITLE
Gits Pull working for only main branch

### ISSUE THREAD

**Issue by psvkaushik** [psvkaushik/Group50_Proj2#14]
As the title suggests, it only works on the main branch, please consider changing the code such that we can pull from all the branches. @VaishnaviNaik96

**Comment by VaishnaviNaik96** [comment]
Hey team,
I have tried fixing this issue, So currently the code works this way: it pulls the difference but it also makes a new directory each time you pull. The issue cannot be fixed right now, but we can work on it in future add-ons of feature. Removing the functionality.
