### ISSUE TITLE
gits_pull does not work for entire repo

### ISSUE THREAD

**Issue by ayush-ai8** [psvkaushik/Group50_Proj2#15]
@VaishnaviNaik96 , Can you please check that the pull code right now asks for a specific filename to pull, in fact let's just pull the entire repo at once.

**Comment by VaishnaviNaik96** [comment]
Hey team,
I have tried fixing this issue, So currently the code works this way: it pulls the difference but it also makes a new directory each time you pull. The issue cannot be fixed right now, but we can work on it in future add-ons of feature. Removing the functionality.
