### ISSUE TITLE
Check_branch does not have a distinction between valid and invalid return code.

### ISSUE THREAD

**Issue by ayush-ai8** [psvkaushik/Group50_Proj2#17]
Hi @psvkaushik ,

In the code of check_status, we need to identify the status code that it returns if the branch exists vs when it does not exist. Please correct it so that it can be integrated with the flask.

**Comment by psvkaushik** [comment]
Hello @ayush-ai8 ,

The success return code 200 for check branch. They've not been included in the code to avoid redundancy. But I think I'll add all the expected response/status codes in the docstring to make it easier for UI integration.

**Comment by ayush-ai8** [comment]
@psvkaushik Thanks for the upadate. I have to handle them separately , that's why i needed clarity on the same.
