### ISSUE TITLE
Prettify code Yaml failing in GitHub Actions

### ISSUE THREAD

**Issue by psvkaushik** [psvkaushik/Group50_Proj2#24]
Hello @VaishnaviNaik96 ,

There seems to be an issue with the prettify library being used and it keep failing everyrun. I tried to change the version to see if it works, but it raised a new lot of error. 
Please look into it and fix it.

**Comment by VaishnaviNaik96** [comment]
Hey team,
I have tried fixing this issue, So currently the code works this way: it pulls the difference but it also makes a new directory each time you pull. The issue cannot be fixed right now, but we can work on it in future add-ons of feature. Removing the functionality.
