### ISSUE TITLE
Gits_push, there is no description, and it doesn't work when wanting to push to a branch which is not main.

### ISSUE THREAD

**Issue by VaishnaviNaik96** [psvkaushik/Group50_Proj2#30]

**Comment by psvkaushik** [comment]
Thank for pointing that out, we've identified the issue and will push the changes soon.

**Comment by psvkaushik** [comment]
The code is now updated to show the function description. Regarding the pushing to a branch other than main, that will be an enhancement we'll roll out in the future.

**Comment by ayush-ai8** [comment]
The code has been modified to take advantage of the branch as an input. Closing for now as even the enhancement is in place.
