### ISSUE TITLE
Commit count and merge do not return anything to the caller function.

### ISSUE THREAD

**Issue by ayush-ai8** [psvkaushik/Group50_Proj2#36]
@SuryaUpadyayula, the scripts mentioned above, do not return any response after performing the actions.
Can you make sure the library functions return the response?

**Comment by SuryaUpadyayula** [comment]
Hey Ayush, 

gits_count_commit should return the count in the 'commit_count' variable. 

Updated the gits_merge to return the status instead of print it out. 

Let me know if these changes are working with the frontend. If not, I can work on them further and update the codes.

**Comment by ayush-ai8** [comment]
I got the returns as expected., thanks for updating the functions.
