### ISSUE TITLE
Create Repo is always failing.

### ISSUE THREAD

**Issue by ayush-ai8** [psvkaushik/Group50_Proj2#5]
I have tried to use create repo library, but could not get it working, can you shed some light on the variables, and can we make all the fields as variables to be used across the code base. Instead of modifying the scipt.

**Comment by psvkaushik** [comment]
Do you mean there is an issue with the functionality test case for create repo or the script create_repo.py? 
Also the script has been updated to have a description of the variables and what it's functionality is supposed to be.

**Comment by ayush-ai8** [comment]
Thanks for the update, the description has helped me understand the working to integrate it with the frontend.
