### ISSUE TITLE
Test cases are failing after latest commit to app.

### ISSUE THREAD

**Issue by ayush-ai8** [psvkaushik/Group50_Proj2#91]
HI @psvkaushik ,

Can you please have a look at failing test cases or revert your changes if they were accidental, as they are breaking the build.

**Comment by psvkaushik** [comment]
Hello ayush, thanks for pointing it out. There was an issue with the was the response was being returned in the app.py. It is fixed now.

**Comment by psvkaushik** [comment]
Hello @ayush-ai8, 
The code has been updated and it is passing all the test case for now.
